AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    -  bin/**/*
    -  node_modules/**/*
    -  vendor/**/*

require:
  - rubocop-rails
  - rubocop-performance

Layout/IndentationStyle:
  IndentationWidth: 2

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['^ *#']
  Exclude:
    - config/routes.rb

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - config/routes.rb
    - config/environments/production.rb

Metrics/ClassLength:
  Max: 350

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 200

Naming/RescuedExceptionsVariableName:
  Enabled: false

Performance/Casecmp:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/WhereExists:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: false

Style/NegatedIf:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true